[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "etl-job"
version = "1.0.0"
description = "ETL job for loading raw Customer and Order data"
authors = ["Your Name"]

[tool.poetry.dependencies]
pyspark = "^3.2.0"
delta = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"