[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "order-processing-pipeline"
version = "1.0.0"
description = "A PySpark-based data pipeline for processing customer and order data with SCD Type 2"
authors = [
    {name = "Data Engineering Team", email = "data-engineering@example.com"}
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = ["pytest>=7.0.0"]

[tool.pytest]
testpaths = ["tests"]