[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scd_type2_data_pipeline"
version = "0.1.0"
description = "Databricks PySpark pipeline for SCD Type 2 implementation"
authors = [
    {name = "Enterprise Data Engineering Team", email = "data.engineering@example.com"}
]