[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "databricks_etl_pipeline"
version = "1.0.0"
description = "ETL Pipeline for Customer and Order Data Processing in Databricks"
authors = [
    {name = "Databricks Data Engineering Team", email = "data.engineering@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"

[project.dependencies]
pyspark = ">=3.3.0"
delta-spark = ">=2.2.0"