[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyspark_template"
version = "1.0.0"
description = "A PySpark template project"

[tool.poetry.dependencies]
python = "^3.8"
pyspark = "^3.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[tool.poetry.urls]
homepage = "https://example.com"
repository = "https://github.com/example/pyspark_template"
