[tool.poetry]
name = "dlt-pipeline"
version = "1.0.0"
description = "A Delta Live Tables pipeline for customer and order data"
authors = ["Your Name"]

[tool.poetry.dependencies]
pyspark = "^3.1.2"
delta-lake = "^1.0.0"
apache-spark-sql = "^3.1.2"
pytest = "^6.2.5"

[tool.poetry.dev-dependencies]