[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dlt_customer_order_pipeline"
version = "0.1.0"
description = "Delta Live Tables pipeline for customer and order data processing"
authors = [
    {name = "Data Engineering Team", email = "data-engineering@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"