[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "customer_order_delta_pipeline"
version = "1.0.0"
description = "Delta Lake Pipeline for Customer and Order data processing with SCD Type 2"
authors = [
    {name = "Data Engineering Team", email = "dataeng@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.dependencies]
pyspark = "^3.3.0"
delta-spark = "^2.1.0"

[project.dev-dependencies]
pytest = "^7.3.1"
pandas = "^1.5.3"

[tool.pytest.ini_options]
testpaths = ["tests"]