%sql
-- Create the Finance table structure
-- This creates the target Finance table with appropriate data types

CREATE TABLE IF NOT EXISTS Finance.Finance_Data (
  Client STRING,
  CompanyCode STRING,
  FiscalYear INT,
  Period INT,
  DocumentNumber STRING,
  FiscalYearDocument INT,
  GLAccount STRING,
  CostCenter STRING,
  ProfitCenter STRING,
  FunctionalArea STRING,
  BusinessArea STRING,
  ControllingArea STRING,
  DebitCreditIndicator STRING,
  AmountInLocalCurrency DECIMAL(17,2),
  AmountInGroupCurrency DECIMAL(17,2),
  AmountInTransactionCurrency DECIMAL(17,2),
  AccountAssignment STRING,
  ChartOfAccounts STRING,
  CostElement STRING,
  LocalCurrency STRING,
  GroupCurrency STRING,
  TransactionCurrency STRING,
  LineItem INT,
  ClearingDate DATE,
  ClearingPeriod INT,
  ClearingDocument STRING,
  AssignmentNumber STRING,
  ItemText STRING,
  HouseBank STRING,
  PostingKey STRING,
  AccountType STRING,
  EntityID STRING,
  EntityName STRING,
  EntityType STRING,
  EntityRegion STRING,
  ExchangeRate DECIMAL(17,6),
  GainLossLC DECIMAL(17,2),
  GainLossGC DECIMAL(17,2),
  GainLossTC DECIMAL(17,2),
  OffsetAccount STRING,
  GoldenOffsetAccount STRING,
  ProcessedTimestamp TIMESTAMP
);