%sql
-- Step 1: Create intermediate table s_shared.sales_orders_hdr_itm_lots
-- First, drop the table if it exists to avoid conflicts
DROP TABLE IF EXISTS s_shared.sales_orders_hdr_itm_lots;

-- Create the intermediate table by joining header and item data
CREATE TABLE s_shared.sales_orders_hdr_itm_lots AS
SELECT 
    h.SALES_ORDER_NUMBER,
    h.SALES_ORDER_TYPE,
    h.SALES_ORDER_DATE,
    h.CUSTOMER_NUMBER,
    h.CUSTOMER_NAME,
    h.CUSTOMER_PO_NUMBER,
    h.REQUESTED_DELIVERY_DATE,
    h.PROMISED_DELIVERY_DATE,
    h.SALES_PERSON,
    h.SALES_OFFICE,
    h.SALES_DIVISION,
    h.SALES_GROUP,
    h.SALES_DISTRICT,
    h.DISTRIBUTION_CHANNEL,
    h.DIVISION,
    h.BILLING_BLOCK,
    h.DELIVERY_BLOCK,
    h.CREDIT_STATUS,
    h.OVERALL_STATUS,
    h.REJECTION_STATUS,
    h.CREATED_BY,
    h.CREATED_DATE,
    h.LAST_CHANGED_BY,
    h.LAST_CHANGED_DATE,
    h.CURRENCY_CODE,
    h.EXCHANGE_RATE,
    h.NET_VALUE,
    h.TAX_AMOUNT,
    h.GROSS_VALUE,
    i.SALES_ORDER_ITEM,
    i.MATERIAL_NUMBER,
    i.MATERIAL_DESCRIPTION,
    i.ORDER_QUANTITY,
    i.SALES_UNIT,
    i.NET_PRICE,
    i.NET_VALUE AS ITEM_NET_VALUE,
    i.PLANT,
    i.STORAGE_LOCATION,
    i.SHIPPING_POINT,
    i.ROUTE,
    i.CUSTOMER_MATERIAL_NUMBER,
    i.ITEM_CATEGORY,
    i.ITEM_TYPE,
    i.PRICING_GROUP,
    i.PRODUCT_HIERARCHY,
    i.MATERIAL_GROUP,
    i.MATERIAL_GROUP_1,
    i.MATERIAL_GROUP_2,
    i.MATERIAL_GROUP_3,
    i.MATERIAL_GROUP_4,
    i.MATERIAL_GROUP_5,
    i.BATCH_NUMBER,
    i.CONFIRMED_QUANTITY,
    i.DELIVERED_QUANTITY,
    i.OPEN_QUANTITY,
    i.REJECTED_QUANTITY,
    i.REASON_FOR_REJECTION,
    i.ITEM_STATUS,
    i.ITEM_BILLING_BLOCK,
    i.ITEM_DELIVERY_BLOCK,
    i.REQUESTED_DELIVERY_DATE AS ITEM_REQUESTED_DELIVERY_DATE,
    i.CONFIRMED_DELIVERY_DATE,
    i.ACTUAL_DELIVERY_DATE,
    i.GOODS_ISSUE_DATE,
    i.CREATED_BY AS ITEM_CREATED_BY,
    i.CREATED_DATE AS ITEM_CREATED_DATE,
    i.LAST_CHANGED_BY AS ITEM_LAST_CHANGED_BY,
    i.LAST_CHANGED_DATE AS ITEM_LAST_CHANGED_DATE,
    current_timestamp() AS ETL_CREATED_DATE,
    'INITIAL_LOAD' AS ETL_CREATED_BY,
    current_timestamp() AS ETL_UPDATED_DATE,
    'INITIAL_LOAD' AS ETL_UPDATED_BY
FROM 
    b_lots.plooh h
JOIN 
    b_lots.plool i ON h.SALES_ORDER_NUMBER = i.SALES_ORDER_NUMBER
WHERE 
    h.DATA_OPERATION <> 'D'
    AND i.DATA_OPERATION <> 'D';

-- Step 2: Create main sales_orders table
DROP TABLE IF EXISTS sales_orders;

CREATE TABLE sales_orders AS
WITH site_info AS (
    SELECT 
        s.SALES_ORDER_NUMBER,
        s.SALES_ORDER_ITEM,
        a.SITE_ID,
        l.LOCATION_ID
    FROM 
        s_shared.sales_orders_hdr_itm_lots s
    LEFT JOIN 
        b_lots.ploal a ON s.PLANT = a.PLANT_CODE
    LEFT JOIN 
        b_lots.plosl l ON s.STORAGE_LOCATION = l.STORAGE_LOCATION_CODE AND s.PLANT = l.PLANT_CODE
),
campaign_info AS (
    SELECT 
        c.SALES_ORDER_NUMBER,
        c.SALES_ORDER_ITEM,
        c.CAMPAIGN_ID,
        c.CAMPAIGN_NAME,
        c.PROMOTION_ID,
        c.PROMOTION_NAME
    FROM 
        b_lots.plcam c
),
payment_info AS (
    SELECT 
        p.CUSTOMER_NUMBER,
        p.PAYMENT_METHOD,
        p.PAYMENT_TERMS,
        p.PAYMENT_DAYS
    FROM 
        b_lots.plpms p
),
hierarchy_info AS (
    SELECT 
        h.MATERIAL_NUMBER,
        h.PRODUCT_HIERARCHY_LEVEL_1,
        h.PRODUCT_HIERARCHY_LEVEL_2,
        h.PRODUCT_HIERARCHY_LEVEL_3,
        h.PRODUCT_HIERARCHY_LEVEL_4,
        h.PRODUCT_HIERARCHY_LEVEL_5
    FROM 
        b_lots.phihm h
),
eco_info AS (
    SELECT 
        e.MATERIAL_NUMBER,
        e.ECO_TIER,
        e.SUSTAINABILITY_SCORE,
        e.CARBON_FOOTPRINT
    FROM 
        b_lots.lecotw1 e
),
currency_conversion AS (
    SELECT 
        cc.CURRENCY_CODE,
        cc.CONVERSION_DATE,
        cc.CONVERSION_RATE,
        cc.TARGET_CURRENCY
    FROM 
        s_shared.currency_conversion cc
    WHERE 
        cc.TARGET_CURRENCY = 'USD'
)
SELECT 
    s.SALES_ORDER_NUMBER,
    s.SALES_ORDER_ITEM,
    s.SALES_ORDER_TYPE,
    s.SALES_ORDER_DATE,
    s.CUSTOMER_NUMBER,
    s.CUSTOMER_NAME,
    s.CUSTOMER_PO_NUMBER,
    s.REQUESTED_DELIVERY_DATE,
    s.PROMISED_DELIVERY_DATE,
    s.SALES_PERSON,
    s.SALES_OFFICE,
    s.SALES_DIVISION,
    s.SALES_GROUP,
    s.SALES_DISTRICT,
    s.DISTRIBUTION_CHANNEL,
    s.DIVISION,
    s.BILLING_BLOCK,
    s.DELIVERY_BLOCK,
    s.CREDIT_STATUS,
    s.OVERALL_STATUS,
    s.REJECTION_STATUS,
    s.MATERIAL_NUMBER,
    s.MATERIAL_DESCRIPTION,
    s.ORDER_QUANTITY,
    s.SALES_UNIT,
    s.NET_PRICE,
    s.ITEM_NET_VALUE,
    s.PLANT,
    s.STORAGE_LOCATION,
    s.SHIPPING_POINT,
    s.ROUTE,
    s.CUSTOMER_MATERIAL_NUMBER,
    s.ITEM_CATEGORY,
    s.ITEM_TYPE,
    s.PRICING_GROUP,
    s.PRODUCT_HIERARCHY,
    s.MATERIAL_GROUP,
    s.MATERIAL_GROUP_1,
    s.MATERIAL_GROUP_2,
    s.MATERIAL_GROUP_3,
    s.MATERIAL_GROUP_4,
    s.MATERIAL_GROUP_5,
    s.BATCH_NUMBER,
    s.CONFIRMED_QUANTITY,
    s.DELIVERED_QUANTITY,
    s.OPEN_QUANTITY,
    s.REJECTED_QUANTITY,
    s.REASON_FOR_REJECTION,
    s.ITEM_STATUS,
    s.ITEM_BILLING_BLOCK,
    s.ITEM_DELIVERY_BLOCK,
    s.ITEM_REQUESTED_DELIVERY_DATE,
    s.CONFIRMED_DELIVERY_DATE,
    s.ACTUAL_DELIVERY_DATE,
    s.GOODS_ISSUE_DATE,
    s.CURRENCY_CODE,
    s.EXCHANGE_RATE,
    s.NET_VALUE,
    s.TAX_AMOUNT,
    s.GROSS_VALUE,
    -- Site information derived from joins
    si.SITE_ID,
    si.LOCATION_ID,
    -- Campaign information
    ci.CAMPAIGN_ID,
    ci.CAMPAIGN_NAME,
    ci.PROMOTION_ID,
    ci.PROMOTION_NAME,
    -- Payment information
    pi.PAYMENT_METHOD,
    pi.PAYMENT_TERMS,
    pi.PAYMENT_DAYS,
    -- Product hierarchy details
    hi.PRODUCT_HIERARCHY_LEVEL_1,
    hi.PRODUCT_HIERARCHY_LEVEL_2,
    hi.PRODUCT_HIERARCHY_LEVEL_3,
    hi.PRODUCT_HIERARCHY_LEVEL_4,
    hi.PRODUCT_HIERARCHY_LEVEL_5,
    -- Eco information
    ei.ECO_TIER,
    ei.SUSTAINABILITY_SCORE,
    ei.CARBON_FOOTPRINT,
    -- Currency conversion
    CASE 
        WHEN cc.CONVERSION_RATE IS NOT NULL THEN s.NET_VALUE * cc.CONVERSION_RATE
        ELSE s.NET_VALUE
    END AS NET_VALUE_USD,
    CASE 
        WHEN cc.CONVERSION_RATE IS NOT NULL THEN s.GROSS_VALUE * cc.CONVERSION_RATE
        ELSE s.GROSS_VALUE
    END AS GROSS_VALUE_USD,
    -- Calculated fields
    DATEDIFF(s.ACTUAL_DELIVERY_DATE, s.REQUESTED_DELIVERY_DATE) AS DELIVERY_LEAD_TIME,
    CASE 
        WHEN s.ACTUAL_DELIVERY_DATE <= s.PROMISED_DELIVERY_DATE THEN 1
        ELSE 0
    END AS ON_TIME_DELIVERY_FLAG,
    CASE 
        WHEN s.REJECTED_QUANTITY > 0 THEN s.REJECTED_QUANTITY / NULLIF(s.ORDER_QUANTITY, 0)
        ELSE 0
    END AS REJECTION_RATE,
    -- Audit columns
    s.CREATED_BY,
    s.CREATED_DATE,
    s.LAST_CHANGED_BY,
    s.LAST_CHANGED_DATE,
    current_timestamp() AS ETL_CREATED_DATE,
    'INITIAL_LOAD' AS ETL_CREATED_BY,
    current_timestamp() AS ETL_UPDATED_DATE,
    'INITIAL_LOAD' AS ETL_UPDATED_BY
FROM 
    s_shared.sales_orders_hdr_itm_lots s
LEFT JOIN 
    site_info si ON s.SALES_ORDER_NUMBER = si.SALES_ORDER_NUMBER AND s.SALES_ORDER_ITEM = si.SALES_ORDER_ITEM
LEFT JOIN 
    campaign_info ci ON s.SALES_ORDER_NUMBER = ci.SALES_ORDER_NUMBER AND s.SALES_ORDER_ITEM = ci.SALES_ORDER_ITEM
LEFT JOIN 
    payment_info pi ON s.CUSTOMER_NUMBER = pi.CUSTOMER_NUMBER
LEFT JOIN 
    hierarchy_info hi ON s.MATERIAL_NUMBER = hi.MATERIAL_NUMBER
LEFT JOIN 
    eco_info ei ON s.MATERIAL_NUMBER = ei.MATERIAL_NUMBER
LEFT JOIN 
    currency_conversion cc ON s.CURRENCY_CODE = cc.CURRENCY_CODE AND DATE(s.SALES_ORDER_DATE) = DATE(cc.CONVERSION_DATE);

-- Optimize the tables for better query performance
OPTIMIZE s_shared.sales_orders_hdr_itm_lots ZORDER BY (SALES_ORDER_NUMBER, SALES_ORDER_DATE);
OPTIMIZE sales_orders ZORDER BY (SALES_ORDER_NUMBER, SALES_ORDER_DATE, CUSTOMER_NUMBER);